apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dplysb
  name: dplysb-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dplysb
  strategy: {}
  template:
    metadata:
      labels:
        app: dplysb
    spec:
      containers:
      - image: sahahub/springboot:latest
        name: springboot-container
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
status: {}
