apiVersion: v1
kind: Service
metadata:
  name: dplysb
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  selector:
    app: dplysb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
